-- قاعدة البيانات المشتركة لموقع مذاكرتك
-- شغّل الملف كاملًا مرة واحدة في Supabase > SQL Editor

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null default 'طالب',
  password_hash text not null,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_content (
  id integer primary key,
  teachers jsonb not null default '[]'::jsonb,
  removed jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.site_content (id, teachers, removed)
values (1, '[]'::jsonb, '[]'::jsonb)
on conflict (id) do nothing;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  to_email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  user_name text not null,
  user_email text not null,
  subject text not null,
  category text not null default 'other',
  priority text not null default 'medium',
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id text not null references public.tickets(id) on delete cascade,
  from_role text not null,
  author_name text not null,
  text text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_to_email_created on public.notifications(to_email, created_at desc);
create index if not exists idx_tickets_user_updated on public.tickets(user_id, updated_at desc);
create index if not exists idx_ticket_messages_ticket_created on public.ticket_messages(ticket_id, created_at asc);

-- الحماية: التطبيق يتعامل مع قاعدة البيانات من خلال Service Role على Vercel.
-- لا تضع SUPABASE_SERVICE_ROLE_KEY داخل أي ملف frontend.

alter table public.users enable row level security;
alter table public.site_content enable row level security;
alter table public.notifications enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;
