-- قاعدة بيانات مذاكرتك: حسابات + رتب + تذاكر + إشعارات مشتركة
-- شغّل الملف كاملًا في Supabase SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text,
  phone text,
  username text,
  name text not null default 'طالب',
  role text not null default 'student',
  password_hash text not null,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users alter column email drop not null;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists username text;
alter table public.users add column if not exists role text not null default 'student';
update public.users set role='student' where role is null or role='';

create unique index if not exists users_username_unique on public.users(lower(username)) where username is not null and username <> '';
create unique index if not exists users_phone_unique on public.users(phone) where phone is not null and phone <> '';
create unique index if not exists users_email_unique on public.users(lower(email)) where email is not null and email <> '';
create index if not exists idx_users_role_created on public.users(role, created_at desc);
create index if not exists idx_users_username on public.users(lower(username));

create table if not exists public.site_content (
  id integer primary key,
  teachers jsonb not null default '[]'::jsonb,
  removed jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
insert into public.site_content (id, teachers, removed)
values (1, '[]'::jsonb, '[]'::jsonb)
on conflict (id) do nothing;

-- مدرسون افتراضيون تجريبيون للمنصة (قابلون للتعديل أو الحذف من لوحة الإدارة)
update public.site_content
set teachers = '[
  {"id":"t1","name":"أ/ أحمد سامح","subject":"الرياضيات","bio":"شرح مبسط وتدريب مستمر على مسائل المنهج.","grades":["first","second","third"],"branches":["general","science","literary","science_biology","science_math"]},
  {"id":"t2","name":"أ/ محمد ياسر","subject":"اللغة العربية","bio":"نحو وبلاغة وقراءة مع تدريبات امتحانات.","grades":["first","second","third"],"branches":["general","science","literary","science_biology","science_math"]},
  {"id":"t3","name":"أ/ عمر خالد","subject":"اللغة الإنجليزية","bio":"Grammar + Vocabulary + Practice بطريقة عملية.","grades":["first","second","third"],"branches":["general","science","literary","science_biology","science_math"]},
  {"id":"t4","name":"أ/ كريم عادل","subject":"الفيزياء","bio":"حل مسائل وخطط سريعة للمراجعة النهائية.","grades":["second","third"],"branches":["science","science_math","science_biology"]},
  {"id":"t5","name":"أ/ يوسف حمدي","subject":"الكيمياء","bio":"شرح المفاهيم والتدريب على أسئلة الاختيار من متعدد.","grades":["second","third"],"branches":["science","science_math","science_biology"]},
  {"id":"t6","name":"أ/ مصطفى نادر","subject":"الأحياء","bio":"مراجعات مركزة ورسومات توضيحية وأسئلة بنك.","grades":["second","third"],"branches":["science_biology","science"]},
  {"id":"t7","name":"أ/ شريف محمود","subject":"التاريخ","bio":"مراجعات منظمة وربط الأحداث بأسئلة الامتحانات.","grades":["second","third"],"branches":["literary"]},
  {"id":"t8","name":"أ/ حسام فتحي","subject":"الجغرافيا","bio":"خرائط ومفاهيم وتدريب على أسئلة السنوات السابقة.","grades":["second","third"],"branches":["literary"]},
  {"id":"t9","name":"أ/ ياسين رجب","subject":"الفلسفة والمنطق","bio":"تبسيط الأفكار وتدريب على أسئلة المقال والاختيار.","grades":["second","third"],"branches":["literary"]},
  {"id":"t10","name":"أ/ محمود طارق","subject":"العلوم المتكاملة","bio":"مراجعات قصيرة وأسئلة تدريبية مناسبة للمسار.","grades":["first"],"branches":["general"]}
]'::jsonb
where id = 1 and jsonb_array_length(teachers) = 0;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  to_email text,
  to_user_id bigint references public.users(id) on delete cascade,
  to_role text,
  created_at timestamptz not null default now()
);

alter table public.notifications alter column to_email drop not null;
alter table public.notifications add column if not exists to_user_id bigint references public.users(id) on delete cascade;
alter table public.notifications add column if not exists to_role text;

create index if not exists idx_notifications_user_created on public.notifications(to_user_id, created_at desc);
create index if not exists idx_notifications_role_created on public.notifications(to_role, created_at desc);
create index if not exists idx_notifications_to_email_created on public.notifications(to_email, created_at desc);

create table if not exists public.tickets (
  id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  user_name text not null,
  user_email text,
  subject text not null,
  category text not null default 'other',
  priority text not null default 'medium',
  status text not null default 'open',
  assigned_role text not null default 'support',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tickets alter column user_email drop not null;
alter table public.tickets add column if not exists assigned_role text not null default 'support';
create index if not exists idx_tickets_user_updated on public.tickets(user_id, updated_at desc);
create index if not exists idx_tickets_assigned_updated on public.tickets(assigned_role, updated_at desc);

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id text not null references public.tickets(id) on delete cascade,
  from_role text not null,
  author_name text not null,
  text text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_ticket_messages_ticket_created on public.ticket_messages(ticket_id, created_at asc);

alter table public.users enable row level security;
alter table public.site_content enable row level security;
alter table public.notifications enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;

-- التطبيق يستخدم SUPABASE_SERVICE_ROLE_KEY في Vercel، لذلك لا تضع هذا المفتاح داخل الواجهة.


-- شات خاص بالإدارة/فريق الدعم
create table if not exists public.admin_chat_messages (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  author_name text not null,
  author_role text not null,
  text text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_admin_chat_created on public.admin_chat_messages(created_at asc);
alter table public.admin_chat_messages enable row level security;


-- سجل نشاط الموقع: يراه الـ OWNER فقط عبر الـAPI
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id) on delete set null,
  actor_name text not null,
  actor_role text not null default 'guest',
  action text not null,
  target_user_id bigint references public.users(id) on delete set null,
  target_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists idx_audit_logs_created on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_actor_created on public.audit_logs(actor_user_id, created_at desc);
create index if not exists idx_audit_logs_action_created on public.audit_logs(action, created_at desc);
alter table public.audit_logs enable row level security;


-- الاختبارات والأسئلة والنتائج
create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  title text not null,
  subject text not null default '',
  description text not null default '',
  grade text,
  branch text,
  duration_minutes integer not null default 30,
  is_published boolean not null default false,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_exams_published_created on public.exams(is_published, created_at desc);
create index if not exists idx_exams_track on public.exams(grade, branch, created_at desc);

create table if not exists public.exam_questions (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  text text not null,
  options jsonb not null default '[]'::jsonb,
  correct_index integer not null,
  points integer not null default 1,
  created_at timestamptz not null default now()
);
create index if not exists idx_exam_questions_exam on public.exam_questions(exam_id, id);

create table if not exists public.exam_attempts (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  answers jsonb not null default '{}'::jsonb,
  score integer not null default 0,
  total_points integer not null default 0,
  percent integer not null default 0,
  submitted_at timestamptz not null default now()
);
create index if not exists idx_exam_attempts_user_submitted on public.exam_attempts(user_id, submitted_at desc);

create table if not exists public.question_bank (
  id bigint generated by default as identity primary key,
  text text not null,
  subject text not null default '',
  chapter text not null default '',
  difficulty text not null default 'متوسط',
  grade text,
  branch text,
  options jsonb not null default '[]'::jsonb,
  correct_index integer not null,
  explanation text not null default '',
  points integer not null default 1,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_question_bank_track on public.question_bank(grade, branch, subject, difficulty, created_at desc);
alter table public.question_bank enable row level security;

insert into public.question_bank (text, subject, chapter, difficulty, grade, branch, options, correct_index, explanation, points)
select * from (values
  ('إذا كان 3س + 5 = 20، فما قيمة س؟','الرياضيات','المعادلات','سهل','third','science_math','["3","5","7","10"]'::jsonb,1,'نطرح 5 ثم نقسم على 3، فتكون س = 5.',1),
  ('ما عكس كلمة "نشيط"؟','اللغة العربية','المفردات','سهل','first','general','["كسول","ذكي","سريع","قوي"]'::jsonb,0,'عكس نشيط هو كسول.',1),
  ('Choose the correct form: She ___ to school every day.','اللغة الإنجليزية','Grammar','سهل','second','science','["go","goes","going","gone"]'::jsonb,1,'مع She نستخدم goes في المضارع البسيط.',1),
  ('ما وحدة قياس شدة التيار الكهربائي؟','الفيزياء','الكهرباء','سهل','third','science_math','["الفولت","الأمبير","الأوم","الوات"]'::jsonb,1,'شدة التيار تقاس بالأمبير.',1),
  ('أي من الآتي يمثل رابطة أيونية؟','الكيمياء','الروابط الكيميائية','متوسط','third','science_biology','["NaCl","O2","N2","Cl2"]'::jsonb,0,'كلوريد الصوديوم مثال شائع للرابطة الأيونية.',1),
  ('أي عضو مسؤول بشكل أساسي عن تبادل الغازات في الرئة؟','الأحياء','الجهاز التنفسي','سهل','third','science_biology','["الحويصلات الهوائية","القصبة","البلعوم","الحجاب الحاجز"]'::jsonb,0,'تحدث عملية تبادل الغازات في الحويصلات الهوائية.',1),
  ('في أي قارة تقع دولة مصر؟','التاريخ والجغرافيا','موقع مصر','سهل','second','literary','["آسيا","أفريقيا","أوروبا","أمريكا"]'::jsonb,1,'تقع مصر أساسًا في شمال أفريقيا مع شبه جزيرة سيناء في آسيا.',1),
  ('أي علم يهتم بدراسة الخرائط وتوزيع الظواهر على سطح الأرض؟','الجغرافيا','مدخل الجغرافيا','متوسط','second','literary','["الجغرافيا","الفيزياء","الأحياء","الكيمياء"]'::jsonb,0,'الجغرافيا تدرس المكان والظواهر وتوزيعها على سطح الأرض.',1),
  ('الاستدلال الذي ينتقل من الكليات إلى الجزئيات يسمى؟','الفلسفة والمنطق','الاستدلال','متوسط','third','literary','["استقراء","استنباط","ملاحظة","وصف"]'::jsonb,1,'الاستنباط ينتقل من قاعدة عامة إلى حالة خاصة.',1),
  ('أي مما يلي يُعد مصدرًا للطاقة المتجددة؟','العلوم المتكاملة','الطاقة','سهل','first','general','["الفحم","النفط","الطاقة الشمسية","الغاز الطبيعي"]'::jsonb,2,'الطاقة الشمسية مصدر متجدد.',1)
) as seed(text, subject, chapter, difficulty, grade, branch, options, correct_index, explanation, points)
where not exists (select 1 from public.question_bank limit 1);

alter table public.exams enable row level security;
alter table public.exam_questions enable row level security;
alter table public.exam_attempts enable row level security;
