-- قاعدة بيانات مذاكرتك: حسابات + رتب + تذاكر + إشعارات مشتركة
-- شغّل الملف كاملًا في Supabase SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text,
  phone text,
  name text not null default 'طالب',
  role text not null default 'student',
  password_hash text not null,
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users alter column email drop not null;
alter table public.users add column if not exists phone text;
alter table public.users add column if not exists role text not null default 'student';
update public.users set role='student' where role is null or role='';

create unique index if not exists users_phone_unique on public.users(phone) where phone is not null and phone <> '';
create unique index if not exists users_email_unique on public.users(lower(email)) where email is not null and email <> '';
create index if not exists idx_users_role_created on public.users(role, created_at desc);

create table if not exists public.site_content (
  id integer primary key,
  teachers jsonb not null default '[]'::jsonb,
  removed jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
insert into public.site_content (id, teachers, removed)
values (1, '[]'::jsonb, '[]'::jsonb)
on conflict (id) do nothing;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null default '',
  to_email text,
  to_user_id bigint references public.users(id) on delete cascade,
  to_role text,
  created_at timestamptz not null default now()
);

alter table public.notifications alter column to_email drop not null;
alter table public.notifications add column if not exists to_user_id bigint references public.users(id) on delete cascade;
alter table public.notifications add column if not exists to_role text;

create index if not exists idx_notifications_user_created on public.notifications(to_user_id, created_at desc);
create index if not exists idx_notifications_role_created on public.notifications(to_role, created_at desc);
create index if not exists idx_notifications_to_email_created on public.notifications(to_email, created_at desc);

create table if not exists public.tickets (
  id text primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  user_name text not null,
  user_email text,
  subject text not null,
  category text not null default 'other',
  priority text not null default 'medium',
  status text not null default 'open',
  assigned_role text not null default 'support',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tickets alter column user_email drop not null;
alter table public.tickets add column if not exists assigned_role text not null default 'support';
create index if not exists idx_tickets_user_updated on public.tickets(user_id, updated_at desc);
create index if not exists idx_tickets_assigned_updated on public.tickets(assigned_role, updated_at desc);

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id text not null references public.tickets(id) on delete cascade,
  from_role text not null,
  author_name text not null,
  text text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_ticket_messages_ticket_created on public.ticket_messages(ticket_id, created_at asc);

alter table public.users enable row level security;
alter table public.site_content enable row level security;
alter table public.notifications enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;

-- التطبيق يستخدم SUPABASE_SERVICE_ROLE_KEY في Vercel، لذلك لا تضع هذا المفتاح داخل الواجهة.


-- شات خاص بالإدارة/فريق الدعم
create table if not exists public.admin_chat_messages (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  author_name text not null,
  author_role text not null,
  text text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_admin_chat_created on public.admin_chat_messages(created_at asc);
alter table public.admin_chat_messages enable row level security;
