const fs=require('fs'), vm=require('vm'), assert=require('assert');
const ctx={console};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('./assets/data.js','utf8'),ctx);
const grades=JSON.parse(vm.runInContext('JSON.stringify(Object.keys(EDU.grades))',ctx));
const first=JSON.parse(vm.runInContext('JSON.stringify(EDU.grades.first.branches.map(x=>x.id))',ctx));
const second=JSON.parse(vm.runInContext('JSON.stringify(EDU.grades.second.branches.map(x=>x.id))',ctx));
const third=JSON.parse(vm.runInContext('JSON.stringify(EDU.grades.third.branches.map(x=>x.id))',ctx));
const label=vm.runInContext('educationBranchLabel("third","science_math")',ctx);
const firstFallback=vm.runInContext('educationBranchLabel("first","bad")',ctx);
assert.deepStrictEqual(grades,['first','second','third']);
assert.deepStrictEqual(first,['general']);
assert.deepStrictEqual(second,['science','literary']);
assert.deepStrictEqual(third,['science_biology','science_math','literary']);
assert.strictEqual(label,'علمي رياضة');
assert.strictEqual(firstFallback,'ثانوي عام — عام');
console.log('education config: OK');
